spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      # none, create-only, drop, create, create-drop, validate, update
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true